"""User

Revision ID: 59aa4bf6aefd
Revises: 6de647ae39d4
Create Date: 2023-12-21 23:03:54.271182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59aa4bf6aefd'
down_revision = '6de647ae39d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('sl_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sl_no', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
