"""inital migration

Revision ID: cd3c632d15fc
Revises: 
Create Date: 2023-12-21 16:46:16.627291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3c632d15fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apparatus',
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sl_no'),
    sa.UniqueConstraint('sl_no')
    )
    op.create_table('chemical',
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sl_no'),
    sa.UniqueConstraint('sl_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chemical')
    op.drop_table('apparatus')
    # ### end Alembic commands ###
